
services:
  esg-issue-service:
    build: .
    container_name: esg-issue-service
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped 